/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import controller.ProductController;
import controller.UserTableController;
import dao.OrderDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.Color; // Add this import for potential UI styling

/**
 *
 * @author sandhya sapkota
 */
public class CustomersOrders extends javax.swing.JFrame {

    /**
     * Creates new form CustomerOrders
     */
    public CustomersOrders() {
        initComponents();
        loadOrderTable();
    }

    // Update the loadOrderTable method to include initial styling:
    private void loadOrderTable() {
        String[] columns = {"P.Id", "Product Name", "CustomerName", "Date", "Price"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        OrderDao orderDao = new OrderDao();
        List<Object[]> orderData = orderDao.getOrderTableData();
        for (Object[] row : orderData) {
            model.addRow(row);
        }
        ReviewList.setModel(model);
        
        // Add search functionality
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        ReviewList.setRowSorter(sorter);
        
        // Set initial placeholder styling
        SearchBar.setForeground(Color.GRAY);
        
        // Add DocumentListener to SearchBar for real-time filtering
        SearchBar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable(sorter);
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable(sorter);
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable(sorter);
            }
        });
    }
    
    // Update the filterTable method to search by first alphabet only:
    private void filterTable(TableRowSorter<DefaultTableModel> sorter) {
        String searchText = SearchBar.getText().trim();
        if (searchText.isEmpty() || searchText.equals("Search")) {
            sorter.setRowFilter(null); // Show all rows
        } else {
            // Get only the first character for searching
            String firstChar = searchText.substring(0, 1);
            
            // Create a list of RowFilters for specific columns - search by first alphabet only
            List<RowFilter<Object, Object>> filters = new ArrayList<>();
            
            // Search in Product Name (column 1) - first alphabet only
            filters.add(RowFilter.regexFilter("(?i)^" + firstChar + ".*", 1));
            
            // Search in Customer Name (column 2) - first alphabet only
            filters.add(RowFilter.regexFilter("(?i)^" + firstChar + ".*", 2));
            
            // Combine filters with OR logic (either product name OR customer name starts with the letter)
            RowFilter<Object, Object> combinedFilter = RowFilter.orFilter(filters);
            sorter.setRowFilter(combinedFilter);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReviewList = new javax.swing.JTable();
        SearchBar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        overviewBtn = new javax.swing.JButton();
        c_ordersBtn = new javax.swing.JButton();
        add_itemsBtn = new javax.swing.JButton();
        user_manageBtn = new javax.swing.JButton();
        reviewBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogoutBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setText("Order List");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        ReviewList.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ReviewList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "P.Id", "Product Name", "CustomerName", "Date", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReviewList.setRowHeight(40);
        ReviewList.setRowMargin(10);
        jScrollPane1.setViewportView(ReviewList);

        SearchBar.setText("Search");
        SearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchBarFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(425, 425, 425)
                        .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        jPanel2.setBackground(new java.awt.Color(217, 217, 217));

        overviewBtn.setBackground(new java.awt.Color(217, 217, 217));
        overviewBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        overviewBtn.setText("Overview");
        overviewBtn.setBorder(null);
        overviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewBtnActionPerformed(evt);
            }
        });

        c_ordersBtn.setBackground(new java.awt.Color(217, 217, 217));
        c_ordersBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        c_ordersBtn.setText("Customer Orders");
        c_ordersBtn.setBorder(null);
        c_ordersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_ordersBtnActionPerformed(evt);
            }
        });

        add_itemsBtn.setBackground(new java.awt.Color(217, 217, 217));
        add_itemsBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        add_itemsBtn.setText("Items");
        add_itemsBtn.setBorder(null);
        add_itemsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_itemsBtnActionPerformed(evt);
            }
        });

        user_manageBtn.setBackground(new java.awt.Color(217, 217, 217));
        user_manageBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        user_manageBtn.setText("User Management");
        user_manageBtn.setBorder(null);
        user_manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_manageBtnActionPerformed(evt);
            }
        });

        reviewBtn.setBackground(new java.awt.Color(217, 217, 217));
        reviewBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        reviewBtn.setText("Review");
        reviewBtn.setBorder(null);
        reviewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewBtnActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trenovix.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo (Custom).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        LogoutBtn1.setBackground(new java.awt.Color(255, 51, 51));
        LogoutBtn1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LogoutBtn1.setText("Logout");
        LogoutBtn1.setBorder(null);
        LogoutBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(overviewBtn)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(c_ordersBtn)
                            .addComponent(add_itemsBtn)
                            .addComponent(reviewBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_manageBtn)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(LogoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(overviewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_ordersBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_itemsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user_manageBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reviewBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn1)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void SearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusGained
        if (SearchBar.getText().equals("Search")) {
            SearchBar.setText("");
        }
    }//GEN-LAST:event_SearchBarFocusGained

    private void SearchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusLost
        if (SearchBar.getText().isEmpty()) {
            SearchBar.setText("Search");
        }
    }//GEN-LAST:event_SearchBarFocusLost

    private void overviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewBtnActionPerformed
        Overview overviewPage = new Overview();
        overviewPage.setLocationRelativeTo(null);
        overviewPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_overviewBtnActionPerformed

    private void c_ordersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_ordersBtnActionPerformed
        CustomersOrders c = new CustomersOrders();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_c_ordersBtnActionPerformed

    private void add_itemsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_itemsBtnActionPerformed
        ItemsPage itemsPage = new ItemsPage();
        ProductController.attachAddProductToItemsPage(itemsPage);
        itemsPage.setLocationRelativeTo(null);
        itemsPage.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_add_itemsBtnActionPerformed

    private void user_manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_manageBtnActionPerformed
        UserManagement userTable = new UserManagement();
        Login login = new Login(); // FIX: create a Login instance
        UserTableController controller = new UserTableController(userTable, login);
        controller.loadUsers();
        userTable.setLocationRelativeTo(null);
        userTable.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_user_manageBtnActionPerformed

    private void reviewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewBtnActionPerformed
        Review reviewsPage = new Review();
        reviewsPage.setLocationRelativeTo(null);
        reviewsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reviewBtnActionPerformed

    private void LogoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtn1ActionPerformed
        Login login = new Login();
        LoginController logincontroller = new LoginController(login);
        logincontroller.open();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomersOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomersOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomersOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomersOrders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomersOrders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn1;
    private javax.swing.JTable ReviewList;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton add_itemsBtn;
    private javax.swing.JButton c_ordersBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton overviewBtn;
    private javax.swing.JButton reviewBtn;
    private javax.swing.JButton user_manageBtn;
    // End of variables declaration//GEN-END:variables
}
