/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import controller.ProductController;
import controller.UserTableController;
import dao.ReviewDao;
import java.util.ArrayList;
import java.util.List;
import java.awt.Color;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author sandhya sapkota
 */
public class Review extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public Review() {
        initComponents();
        loadReviewTable();
    }

    private void loadReviewTable() {
        String[] columns = {"P.Id", "Product Name", "CustomerName", "Date", "Review"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);

        ReviewDao reviewDao = new ReviewDao();
        List<Object[]> reviewData = reviewDao.getReviewTableData();
        for (Object[] row : reviewData) {
            model.addRow(row);
        }
        ReviewList.setModel(model);

        // Enable search/filter - Updated to search only by first alphabet
        TableRowSorter<DefaultTableModel> rowSorter = new TableRowSorter<>(model);
        ReviewList.setRowSorter(rowSorter);

        // Set initial placeholder styling
        SearchBar.setForeground(Color.GRAY);

        SearchBar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { filter(rowSorter); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { filter(rowSorter); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { filter(rowSorter); }
            
            private void filter(TableRowSorter<DefaultTableModel> sorter) {
                String text = SearchBar.getText().trim();
                if (text.length() == 0 || text.equals("Search")) {
                    sorter.setRowFilter(null); // Show all rows
                } else {
                    // Get only the first character for searching
                    String firstChar = text.substring(0, 1);
                    
                    // Create filters for specific columns - search by first alphabet only
                    List<RowFilter<Object, Object>> filters = new ArrayList<>();
                    
                    // Search in Product Name/Dress Name (column 1) - first alphabet only
                    filters.add(RowFilter.regexFilter("(?i)^" + firstChar + ".*", 1));
                    
                    // Search in Customer Name/Username (column 2) - first alphabet only
                    filters.add(RowFilter.regexFilter("(?i)^" + firstChar + ".*", 2));
                    
                    // Combine filters with OR logic (either username OR dress name starts with the letter)
                    RowFilter<Object, Object> combinedFilter = RowFilter.orFilter(filters);
                    sorter.setRowFilter(combinedFilter);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SearchBar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReviewList = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        Order_Logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        OverView = new javax.swing.JButton();
        Orders = new javax.swing.JButton();
        Items = new javax.swing.JButton();
        UserManagement = new javax.swing.JButton();
        Review = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SearchBar.setText("Search");
        SearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchBarFocusLost(evt);
            }
        });

        ReviewList.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        ReviewList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "P.Id", "Product Name", "CustomerName", "Date", "Review"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReviewList.setRowHeight(40);
        ReviewList.setRowMargin(10);
        jScrollPane1.setViewportView(ReviewList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(217, 217, 217));

        Order_Logout.setBackground(new java.awt.Color(255, 0, 0));
        Order_Logout.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Order_Logout.setForeground(new java.awt.Color(255, 255, 255));
        Order_Logout.setText("Logout");
        Order_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Order_LogoutActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/T_Logo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trenovix.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (Custom).png"))); // NOI18N

        OverView.setBackground(new java.awt.Color(217, 217, 217));
        OverView.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        OverView.setText("Overview");
        OverView.setBorder(null);
        OverView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OverViewActionPerformed(evt);
            }
        });

        Orders.setBackground(new java.awt.Color(217, 217, 217));
        Orders.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Orders.setText("Customer Orders");
        Orders.setBorder(null);
        Orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersActionPerformed(evt);
            }
        });

        Items.setBackground(new java.awt.Color(217, 217, 217));
        Items.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Items.setText("Items");
        Items.setBorder(null);
        Items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemsActionPerformed(evt);
            }
        });

        UserManagement.setBackground(new java.awt.Color(217, 217, 217));
        UserManagement.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        UserManagement.setText("User Management");
        UserManagement.setBorder(null);
        UserManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManagementActionPerformed(evt);
            }
        });

        Review.setBackground(new java.awt.Color(217, 217, 217));
        Review.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Review.setText("Review");
        Review.setBorder(null);
        Review.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Review))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Items))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Orders))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(OverView))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Order_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UserManagement))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(OverView)
                .addGap(18, 18, 18)
                .addComponent(Orders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Items)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UserManagement)
                .addGap(18, 18, 18)
                .addComponent(Review)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Order_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusGained
        if (SearchBar.getText().equals("Search")) {
            SearchBar.setText("");
            SearchBar.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_SearchBarFocusGained

    private void SearchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusLost
        if (SearchBar.getText().isEmpty()) {
            SearchBar.setText("Search");
            SearchBar.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_SearchBarFocusLost

    private void OverViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OverViewActionPerformed
        // TODO add your handling code here:
        Overview dashboard = new Overview();
        dashboard.setLocationRelativeTo(null);
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OverViewActionPerformed

    private void OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersActionPerformed
        // TODO add your handling code here:
        CustomersOrders orders = new CustomersOrders();
        orders.setLocationRelativeTo(null);
        orders.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_OrdersActionPerformed

    private void ItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemsActionPerformed
        // TODO add your handling code here:
        ItemsPage itemsPage = new ItemsPage();
        controller.ProductController.attachAddProductToItemsPage(itemsPage);
        itemsPage.setLocationRelativeTo(null);
        itemsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ItemsActionPerformed

    private void UserManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManagementActionPerformed
        UserManagement userTable = new UserManagement();
        Login login = new Login();
        controller.UserTableController controller = new controller.UserTableController(userTable, login);
        controller.loadUsers();
        userTable.setLocationRelativeTo(null);
        userTable.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_UserManagementActionPerformed

    private void ReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReviewActionPerformed
        Review reviewsPage = new Review();
        reviewsPage.setLocationRelativeTo(null);
        reviewsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReviewActionPerformed

    private void Order_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Order_LogoutActionPerformed
        Login login = new Login();
        LoginController logincontroller = new LoginController(login);
        logincontroller.open();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Order_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Review().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Items;
    private javax.swing.JButton Order_Logout;
    private javax.swing.JButton Orders;
    private javax.swing.JButton OverView;
    private javax.swing.JButton Review;
    private javax.swing.JTable ReviewList;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton UserManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    // Add this getter at the end of your class:
    public javax.swing.JTable getTable() {
        return ReviewList;
    }
}
