/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author sandhya sapkota
 */
public class Trending extends JPanel {

    /**
     * Creates new form Trending
     */
    public Trending(String imagePath) {
        setPreferredSize(new Dimension(978, 370));
        setLayout(new BorderLayout());

        homeimage = new JLabel();
        homeimage.setHorizontalAlignment(JLabel.CENTER);
        homeimage.setVerticalAlignment(JLabel.CENTER);

        // --- Debug: Print Resource URL ---
        java.net.URL imgUrl = getClass().getResource(imagePath);
        System.out.println("Loading: " + imagePath + " -> " + imgUrl);

        if (imgUrl != null) {
            ImageIcon icon = new ImageIcon(imgUrl);
            Image img = icon.getImage().getScaledInstance(978, 370, Image.SCALE_SMOOTH);
            homeimage.setIcon(new ImageIcon(img));
            homeimage.setText("");
        } else {
            homeimage.setText("Image not found");
        }

        add(homeimage, BorderLayout.CENTER);
    }

    public Trending() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeimage = new javax.swing.JLabel();

        homeimage.setText("image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeimage, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(homeimage, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeimage;
    // End of variables declaration//GEN-END:variables
}
