/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import controller.UserTableController;
import java.awt.event.ActionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.util.List;
import java.util.ArrayList;
import java.awt.Color;

/**
 *
 * @author sandhya sapkota
 */
public class UserManagement extends javax.swing.JFrame {

    private TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form Orders
     */
    public UserManagement() {
        initComponents();
        setupSearchFunctionality();
    }

    private void setupSearchFunctionality() {
        // Get the current table model
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        // Create and set the sorter
        sorter = new TableRowSorter<>(model);
        jTable1.setRowSorter(sorter);
        
        // Add DocumentListener to SearchBar for real-time filtering
        SearchBar.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterTable();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterTable();
            }
        });
        
        // Set initial placeholder styling
        SearchBar.setForeground(Color.GRAY);
    }

    private void filterTable() {
        String searchText = SearchBar.getText().trim();
        if (searchText.isEmpty() || searchText.equals("Search")) {
            sorter.setRowFilter(null); // Show all rows
        } else {
            // Search only in Username column (column 1)
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText, 1));
        }
    }

    // Method to refresh search when table data is updated
    public void refreshSearch() {
        if (sorter != null) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            sorter = new TableRowSorter<>(model);
            jTable1.setRowSorter(sorter);
            filterTable(); // Re-apply current filter
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SearchBar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        LogoutBtn3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        overviewBTN1 = new javax.swing.JButton();
        ordersBTN1 = new javax.swing.JButton();
        itemsBTN1 = new javax.swing.JButton();
        usersBTN1 = new javax.swing.JButton();
        reviewBTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SearchBar.setText("Search");
        SearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchBarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchBarFocusLost(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Email", "Joined"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(40);
        jTable1.setRowMargin(10);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(217, 217, 217));

        LogoutBtn3.setBackground(new java.awt.Color(255, 0, 0));
        LogoutBtn3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LogoutBtn3.setText("Logout");
        LogoutBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtn3ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logo (Custom).png"))); // NOI18N
        jLabel3.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Trenovix.png"))); // NOI18N
        jLabel4.setText("jLabel2");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/user (Custom).png"))); // NOI18N

        overviewBTN1.setBackground(new java.awt.Color(217, 217, 217));
        overviewBTN1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        overviewBTN1.setText("Overview");
        overviewBTN1.setBorder(null);
        overviewBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewBTN1ActionPerformed(evt);
            }
        });

        ordersBTN1.setBackground(new java.awt.Color(217, 217, 217));
        ordersBTN1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ordersBTN1.setText("Customer Orders");
        ordersBTN1.setBorder(null);
        ordersBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersBTN1ActionPerformed(evt);
            }
        });

        itemsBTN1.setBackground(new java.awt.Color(217, 217, 217));
        itemsBTN1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        itemsBTN1.setText("Items");
        itemsBTN1.setBorder(null);
        itemsBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemsBTN1ActionPerformed(evt);
            }
        });

        usersBTN1.setBackground(new java.awt.Color(217, 217, 217));
        usersBTN1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        usersBTN1.setText("User Management");
        usersBTN1.setBorder(null);
        usersBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usersBTN1ActionPerformed(evt);
            }
        });

        reviewBTN1.setBackground(new java.awt.Color(217, 217, 217));
        reviewBTN1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        reviewBTN1.setText("Review");
        reviewBTN1.setBorder(null);
        reviewBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reviewBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(reviewBTN1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(itemsBTN1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ordersBTN1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(overviewBTN1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usersBTN1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(LogoutBtn3)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(70, 70, 70)
                .addComponent(overviewBTN1)
                .addGap(18, 18, 18)
                .addComponent(ordersBTN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemsBTN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usersBTN1)
                .addGap(18, 18, 18)
                .addComponent(reviewBTN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutBtn3)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtn3ActionPerformed
        Login login = new Login();
        LoginController logincontroller = new LoginController(login);
        logincontroller.open();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_LogoutBtn3ActionPerformed

    private void overviewBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewBTN1ActionPerformed
        // Open Overview page
        Overview overviewPage = new Overview();
        overviewPage.setLocationRelativeTo(null);
        overviewPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_overviewBTN1ActionPerformed

    private void ordersBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersBTN1ActionPerformed
        // Open Customer Orders page
        CustomersOrders ordersPage = new CustomersOrders();
        ordersPage.setLocationRelativeTo(null);
        ordersPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ordersBTN1ActionPerformed

    private void itemsBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemsBTN1ActionPerformed
        // Open Items page
        ItemsPage itemsPage = new ItemsPage();
        controller.ProductController.attachAddProductToItemsPage(itemsPage); // if you have this method
        itemsPage.setLocationRelativeTo(null);
        itemsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemsBTN1ActionPerformed

    private void usersBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usersBTN1ActionPerformed
        // Already on User Management, do nothing or reload if needed
        // If you want to reload the user table, you can do it here
        UserManagement userManagementPage = new UserManagement();
        userManagementPage.setLocationRelativeTo(null);
        userManagementPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usersBTN1ActionPerformed

    private void reviewBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reviewBTN1ActionPerformed
        // TODO add your handling code here:
        Review reviewsPage = new Review();
        reviewsPage.setLocationRelativeTo(null);
        reviewsPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reviewBTN1ActionPerformed

    private void SearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusGained
        if (SearchBar.getText().equals("Search")) {
            SearchBar.setText("");
            SearchBar.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_SearchBarFocusGained

    private void SearchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchBarFocusLost
        if (SearchBar.getText().isEmpty()) {
            SearchBar.setText("Search");
            SearchBar.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_SearchBarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn3;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JButton itemsBTN1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton ordersBTN1;
    private javax.swing.JButton overviewBTN1;
    private javax.swing.JButton reviewBTN1;
    private javax.swing.JButton usersBTN1;
    // End of variables declaration//GEN-END:variables

    // Add this getter at the end of your class:
    public javax.swing.JTable getTable() {
        return jTable1;
    }
    public void addLogoutListener(java.awt.event.ActionListener listener) {
        LogoutBtn3.addActionListener(listener);
    }
}
